In [1]:
from __future__ import print_function
import tensorflow as tf

In [2]:
def run_and_print(x):
    with tf.Session() as sess:
        result = sess.run(x)
        print(result)

In [3]:
row = tf.constant([[1., 2.]])
run_and_print(row)

[[ 1.  2.]]


In [4]:
column = tf.constant([[10.], [20.]])
run_and_print(column)

[[ 10.]
 [ 20.]]


### Addition operator

In [5]:
run_and_print(row + column)

[[ 11.  12.]
 [ 21.  22.]]


In [6]:
run_and_print(column + row)

[[ 11.  12.]
 [ 21.  22.]]


### Multiplication operator

In [7]:
run_and_print(row * column)

[[ 10.  20.]
 [ 20.  40.]]


In [8]:
run_and_print(column * row)

[[ 10.  20.]
 [ 20.  40.]]


In [9]:
run_and_print(column * column)

[[ 100.]
 [ 400.]]


In [10]:
run_and_print(row * row)

[[ 1.  4.]]


### Matrix multiplication

In [11]:
run_and_print(tf.matmul(row, column))

[[ 50.]]


In [12]:
run_and_print(tf.matmul(column, row))

[[ 10.  20.]
 [ 20.  40.]]


### Reduction

In [13]:
matrix = tf.constant([[1., 2.], [3., 4.]])
run_and_print(matrix)

[[ 1.  2.]
 [ 3.  4.]]


In [14]:
run_and_print(tf.reduce_mean(matrix))

2.5


In [15]:
run_and_print(tf.reduce_mean(matrix, 0))

[ 2.  3.]


In [16]:
run_and_print(tf.reduce_mean(matrix, 1))

[ 1.5  3.5]


In [17]:
run_and_print(tf.reduce_sum(matrix, 0, keep_dims=True))

[[ 4.  6.]]


In [18]:
run_and_print(tf.reduce_sum(matrix, 1, keep_dims=True))

[[ 3.]
 [ 7.]]
