In [1]:
import tensorflow as tf

In [5]:
def run_and_print(x, dictionary):
    with tf.Session() as sess:
        result = sess.run(x, feed_dict=dictionary)
        print(result)

In [2]:
x = tf.placeholder("float", 3)

In [4]:
y = x * 2

In [6]:
run_and_print(y, {x: [1,2,3]})

[ 2.  4.  6.]


In [7]:
x = tf.placeholder("float", None)

In [8]:
y = x * 2

In [9]:
run_and_print(y, {x: [1,2,3,4]})

[ 2.  4.  6.  8.]


In [12]:
run_and_print(y, {x: [[1,2,3],[4,5,6]]})

[[  2.   4.   6.]
 [  8.  10.  12.]]


In [13]:
import matplotlib.image as mpimg
import matplotlib.pyplot as plt

/usr/local/lib/python2.7/dist-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')


In [14]:
image = tf.placeholder("uint8", [None, None, 3])

In [16]:
slice = tf.slice(image, [1000, 0, 0], [300, -1, -1])

In [19]:
url = "http://learningtensorflow.com/images/MarshOrchid.jpg"
raw_image_data = mpimg.imread(url)

URLError: <urlopen error [Errno -2] Name or service not known>